### ISSUE TITLE
testing on other piso

### ISSUE THREAD

**Issue by scndthe2nd** [WoolseyWorkshop/WoolseyWorkshop_CircuitPython_74HC165#1]
I'm testing this with 74hc597 later today, i will follow up if this works or fork if needed.

**Comment by woolseyj** [comment]
@scndthe2nd, how did the 74hc597 test go?

**Comment by scndthe2nd** [comment]
Hi,


I ended up going with the built-in keypad  library, but all my problems
started because i didn't know what i was doing.

Looks like it works fine now, but i need to check back and see if it works
on the 579, from what i can tell, it should.


Thanks,

Tony Scinta (he/him)
